services:
  db:
    image: postgres:12.7
    container_name: postgres_db
    environment:
      POSTGRES_USER: itbatps
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5666:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
